<cfquery name="getPP" datasource="#dsn#">
    

SELECT PP.PROJECT_NUMBER
	,PP.PROJECT_ID
	,ISNULL(AMOUNT, 0) AMOUNT_DEPO
	,ISNULL(MA1, 0) AMOUNT_FATURA
	,PP.PROJECT_HEAD
	,PP.TARGET_START
FROM #dsn#.PRO_PROJECTS AS PP
LEFT JOIN (
	SELECT SUM(AMOUNT) AMOUNT
		,PROJECT_ID
	FROM (
		SELECT SUM(AMOUNT) AMOUNT
			,PROJECT_ID
		FROM #dsn2#.STOCK_FIS AS SF
		LEFT JOIN #dsn2#.STOCK_FIS_ROW AS SFR ON SFR.FIS_ID = SF.FIS_ID
		WHERE SF.DEPARTMENT_IN = 7
			AND SF.LOCATION_IN = 3
		GROUP BY PROJECT_ID
			/*
              BILGI BURAYA BİR ÖNCEKİ YILI EKLEYECEĞİZ
            UNION
                SELECT SUM(AMOUNT) AMOUNT,PROJECT_ID FROM #dsn#_2023_2.STOCK_FIS AS SF LEFT JOIN #dsn#_2023_2.STOCK_FIS_ROW AS SFR ON SFR.FIS_ID=SF.FIS_ID WHERE SF.DEPARTMENT_IN=7 AND SF.LOCATION_IN=3 GROUP BY PROJECT_ID
            */
		) AS TS
	GROUP BY PROJECT_ID
	) AS SF ON SF.PROJECT_ID = PP.PROJECT_ID
LEFT JOIN (
	SELECT SUM(AMOUNT) AS MA1
		,IPR.PROJECT_ID
	FROM #dsn#.INVOICE_PROJECT_RELATIONS_PBS IPR
	LEFT JOIN (
		SELECT I.INVOICE_ID
			,SUM(IR.AMOUNT) AS AMOUNT
			,1 AS PERIOD_ID
		FROM #dsn2#.INVOICE AS I
		LEFT JOIN #dsn2#.INVOICE_ROW AS IR ON IR.INVOICE_ID = I.INVOICE_ID
		GROUP BY I.INVOICE_ID
			/*
			UNION 
            BILGI BURAYA ÖNCEKİ DÖNEM GELECEK
		*/
		) AS I ON I.INVOICE_ID = IPR.INVOICE_ID
		AND IPR.INVOICE_PERIOD_ID = I.PERIOD_ID
	GROUP BY IPR.PROJECT_ID
	) AS I ON I.PROJECT_ID = PP.PROJECT_ID
GROUP BY PP.PROJECT_NUMBER
	,PP.PROJECT_ID
	,PP.PROJECT_HEAD
	,AMOUNT
	,TARGET_START
	,MA1
HAVING AMOUNT > 0
	OR AMOUNT - MA1 > 0

</cfquery>

<cf_big_list>
<cfoutput query="getPP">
<tr>
    <td>
        #PROJECT_NUMBER#
    </td>
    <td>
        #AMOUNT#
    </td>
    <td>
        #AMOUNT_FATURA#
    </td>
    <td>
        #AMOUNT-AMOUNT_FATURA#
    </td>
</tr>
</cfoutput>
</cf_big_list>