<cfquery name="gets" datasource="#dsn2#">
    SELECT SUM(STOCK_IN-STOCK_OUT) AS BAK,SR.STOCK_ID,S.PRODUCT_CODE,S.PRODUCT_NAME FROM STOCKS_ROW SR
    LEFT JOIN #DSN3#.STOCKS AS S ON S.STOCK_ID=SR.STOCK_ID
    WHERE STORE=7 AND STORE_LOCATION=7 GROUP BY SR.STOCK_ID,S.PRODUCT_CODE,S.PRODUCT_NAME
</cfquery>

<cfdump var="#gets#">
